-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgm7jCQcxF30aLi14l
oG+oqo+nfqjltUimJBrERjkUa/CgCgYIKoZIzj0DAQehRANCAAQuwMscUMqmkHlv
WaremMz3ZhkF53zMMeWmesKOHWgGKywT28EOeeLfnftXVnQVDErGgaHu1+uKrw44
sV5+ex7w
-----END PRIVATE KEY-----